# Generated by Django 6.0.6 on 2026-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_transactionhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
