# Generated by Django 6.0.6 on 2026-07-16 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_transactionhistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
