# Generated by Django 6.0.6 on 2026-07-16 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_livestream_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 17, 14, 15, 7, 991119, tzinfo=datetime.timezone.utc)),
        ),
    ]
