# Generated by Django 6.0.6 on 2026-07-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_profile_balance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
