# Generated by Django 6.0.6 on 2026-07-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
