from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'), 
    path('discover/', views.discover, name='discover'),
    path('friends/', views.friends_list, name='friends_list'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/follow/<str:username>/', views.follow_user, name='follow_user'),
    path('login/', views.login_view, name='login'), 
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'), 
    path('groups/', views.groups_list, name='groups_list'),
    path('group/create/', views.create_group, name='create_group'), 
    path('group/<int:group_id>/', views.group_chat, name='group_chat'),
    path('group/<int:group_id>/join/', views.join_group, name='join_group'),
    path('notifications/', views.notifications, name='notifications'), 
    path('menu/', views.menu, name='menu'),
    path('story/add/', views.create_story, name='create_story'), 
    path('story/<int:story_id>/', views.view_story, name='view_story'),
    path('post/create/', views.create_post, name='create_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'), 
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/share/', views.share_post, name='share_post'),
    path('messages/', views.messages, name='messages'), 
    path('messages/<str:username>/', views.chat_view, name='chat'),
    path('friend-request/send/<str:username>/', views.send_friend_request, name='send_friend_request'),
    path('friend-request/accept/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friend-request/decline/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('friend/cancel/<int:request_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('reels/', views.reels, name='reels'),
    path('reel/upload/', views.upload_reel, name='upload_reel'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('pages/', views.pages_list, name='pages_list'),
    path('page/<int:page_id>/', views.page_view, name='page_view'),
    path('comment/<int:comment_id>/reply/', views.reply_comment, name='reply_comment'),
    path('post/<int:post_id>/save/', views.save_post, name='save_post'),
    path('search/', views.search, name='search'),
    path('live/', views.go_live, name='go_live'),
]
